export default jobs = [
    {
        company: 'Eveo',
        city: 'San Francisco',
        start: '2015',
        end: '2015',
        duration: '5 months',
        title: 'Frontend',
        bullets: [
            'Built banner ads using Flash/Actionscript',
            'Wrote Jade templates for mobile app',
            'Built microsite for use in 3rd party iPad software',
        ],
    },
    // {
    //     company: 'Krafted By Us',
    //     city: 'Martinez',
    //     start: '2015',
    //     end: '2015',
    //     duration: '2 months',
    //     title: 'Frontend',
    //     bullets: [
    //         'Built microsite with Node, Gulp and Sass/Bourbon',
    //     ],
    // },
    {
        company: 'Pixelette Studios',
        city: 'Berkeley',
        start: '2014',
        end: '2015',
        duration: '1 year, 2 months',
        title: 'Frontend',
        bullets: [
            'Built expandable and polite-loading rich-media creatives for DoubleClick and MediaMind (now Sizemek) platforms',
        ],
    },
    {
        company: 'Cibo Studios',
        city: 'San Francisco',
        start: '2013',
        end: '2013',
        duration: '1 month',
        title: 'Frontend',
        bullets: [
            'Built expandable rich-media creatives using Actionscript on DoubleClick platform',
        ],
    },
    {
        company: 'Storefront Political Media',
        city: 'San Francisco',
        start: '2013',
        end: '2013',
        duration: '1 month',
        title: 'Frontend',
        bullets: [
            'Built Flash banner ads in various sizes',
        ],
    },
    {
        company: 'Creative Lift',
        city: 'San Francisco',
        start: '2010',
        end: '2012',
        duration: '2 years',
        title: 'Frontend/iOS',
        bullets: [
            'Maintained and facilitated updates and promotions for Flash application created with AS3 and PureMVC framework which allowed customers to order localized cable, internet and telephone service bundles',
            'Built the Lift Calculator, a simple app for iPhone, for calculating the response rate for marketing campaigns and comparing them to industry averages.',
            'Built Flash banners for various clients',
            'Built landing pages and email campaigns',
        ],
    },
    {
        company: 'Teak Motion Visuals',
        city: 'San Francisco',
        start: '2010',
        end: '2010',
        duration: '4 months',
        title: 'Frontend',
        bullets: [
            'Built Flash banner campaigns',
        ],
    },
    {
        company: 'Attik',
        city: 'San Francisco',
        start: '2010',
        end: '2010',
        duration: '4 months',
        title: 'Frontend',
        bullets: [
            'Built XML driven interactive expandable rich media Flash banners for online reality show',
        ],
    },
    {
        company: 'Eleven',
        city: 'San Francisco',
        start: '2010',
        end: '2010',
        duration: '2 months',
        title: 'Frontend',
        bullets: [
            'Built standard and expandable interactive Flash banners',
        ],
    },
    {
        company: 'Eveo',
        city: 'San Francisco',
        start: '2008',
        end: '2009',
        duration: '4 months',
        title: 'Frontend',
        bullets: [
            'Built 3 Flash interactive video case studies to be used as marketing materials for pharmaceutical companies',
        ],  
    },
    {
        company: 'Graphic Language',
        city: 'San Francisco',
        start: '2006',
        end: '2008',
        duration: '2 years',
        title: 'Frontend',
        bullets: [
            'Built out client web sites using HTML, CSS, JavaScript, Flash and ActionScript',
            'Gathered some experience creating email templates for a CMS-based email software',
        ],
    },
    {
        company: 'Illuminotion',
        city: 'Berkeley',
        start: '2001',
        end: '2006',
        duration: '5 years',
        title: 'Frontend',
        bullets: [
            'Built out all client sites from existing design composites (HTML|CSS|JS|AS)',
        ],
    }
]