export const dark = {
    dark: true,
    colors: {
        background: '#000',
        backgroundTransparent: '#00000000',
        border: '#aaa',
        buttonLabel: '#fff',
        buttonText: '#fff',
        buttonDefault: '#00a',
        buttonPrimary: '#e97451',
        buttonSecondary: '#aaf',
        buttonDanger: '#f00',
        buttonDisabled: '#aaa',
        brandDark: '#aaa',
        brandLight: '#fff',
        headerPrimary: '#fff',
        headerSecondary: 'yellow',
        screen: '#111',
        shadow: '#fff',
        tabActive: '#f00',
        tabInactive: '#fff',
        tabBackground: '#000',
        textDefault: '#fff',
        userTitle: '#fff',
        modalBackground: '#111',
    },
}

export const light = {
    dark: false,
    colors: {
        background: '#eee',
        backgroundTransparent: '#fffff00',
        border: '#aaa',
        buttonLabel: '#fff',
        buttonText: '#fff',
        buttonDefault: '#00a',
        buttonPrimary: '#e97451',
        buttonSecondary: '#aaf',
        buttonDanger: '#f00',
        buttonDisabled: '#aaa',
        brandDark: '#aaa',
        brandLight: '#000',
        headerPrimary: '#000',
        headerSecondary: 'orange',
        screen: '#fff',
        shadow: '#000',
        tabActive: '#f00',
        tabInactive: '#000',
        tabBackground: '#fff',
        textDefault: '#000',
        userTitle: '#000',
        modalBackground: '#333',
    },
}